# theme: jekyll-theme-hacker

# Use the Hitchens theme remotely
# remote_theme: patdryburgh/hitchens-theme

title: g13e hacks
description: experiments, ideas and more...
icon: /assets/images/icon-512.png
#url: "https://g13e.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

#necessary plugins
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-paginate

# pagination settings
paginate: 3
paginate_path: "/page/:num/"
show_excerpts: true
excerpt_length: 20


# other settings
show_downloads: false
hide_search: true
hide_credits: true
google_analytics: UA-69796574-2